plugins {
	id 'java'
	alias libs.plugins.springframework.boot
	alias libs.plugins.spring.dependency.management
}

group = 'com.ixcamper'
version = '0.0.1-SNAPSHOT'

java {
  sourceCompatibility = libs.versions.java.get()
}

repositories {
	mavenCentral()
}

dependencies {
  	implementation 'org.springframework.boot:spring-boot-starter-web'
  	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

tasks.named('test') {
  useJUnitPlatform()
}

